<?php

namespace AppBundle\Repository;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
{
  return $this
    ->createQueryBuilder('l')
    ->getQuery()
    ->getResult()
  ;
}
}
